name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Check Outdated NPM Packages
      run: npm outdated
    - name: Update Outdated NPM Packages
      run: npm update
    - name: Install Dependencies
      run: npm install
    - name: Run Tests
      run: npm test
